backend:
  name: github # Refer to https://www.netlifycms.org/docs/authentication-backends/ for auth backend list and instructions
  branch: master # Branch to update
  repo: emileber/gatsby-test # Repo for pushing new commits. Make sure to replace with your repo!

media_folder: static/assets
public_folder: assets

# adds an interface for drafting, reviewing, and approving posts
publish_mode: editorial_workflow

collections:
  - name: blog
    label: "Post"
    folder: "content"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}.md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - label: "Post Author"
        name: "author"
        widget: "relation"
        collection: "authors"
        searchFields: ["name.first", "twitterHandle"]
        valueField: "name.first"
        displayFields: ["twitterHandle", "followerCount"]
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Cover Image", name: "cover", widget: "image" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: authors
    label: "Authors"
    label_singular: "Author"
    folder: "data/authors"
    create: true
    extension: yml
    format: yml
    slug: "{{fields.id}}"
    identifier_field: id
    fields:
      - label: "id"
        name: "id"
        widget: "string"
        hint: "Unique identifier used in relations with an event's talks."
        pattern: ['.{5,}', "Must have at least 5 characters"]

      - { label: "Full name", name: "name", widget: "string" }

      - label: "Personal website"
        name: "website"
        widget: "string"
        required: false

      - label: "Github username"
        name: "github"
        widget: "string"
        hint: "Username without the @ sign."
        required: false

      - label: "Twitter handle"
        name: "twitter"
        widget: "string"
        hint: "Handle without the @ sign."
        required: false

      - label: "Short bio"
        name: bio
        widget: "markdown"
        required: false
